'use strict';
const $=id=>document.getElementById(id), names={overview:'Overview',steering:'Steering',camera:'Camera',encoders:'Motors & encoders',imu:'IMU',distance:'Distance',gnss:'GNSS',other:'Other sensors',system:'System / ROS'};
let page='overview', config={}, last={}, alive=false, busy=false, trail=[], encoderPrevious={}, cameraTimer=null, diagTime=0, diag={};
const esc=x=>String(x??'UNAVAILABLE').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,n=2)=>typeof x==='number'&&Number.isFinite(x)?x.toFixed(n):'UNAVAILABLE';
const get=k=>last.ros?.[k]?.value, age=k=>last.ros?.[k]?.age, live=(k,limit=2)=>typeof age(k)==='number'&&age(k)<=limit&&age(k)>=0;
function obj(k){try{let x=get(k);return typeof x==='string'?JSON.parse(x):x||{}}catch{return {}}}
function tile(name,val,kind='measured',note=''){return `<div class="card"><h3>${esc(name)}</h3><div class="number ${kind}">${esc(val)}</div><p class="muted">${esc(note)}</p></div>`}
function rows(keys){return '<div class="scroll"><table><tr><th>Source</th><th>Value</th><th>Age</th><th>Observed Hz</th></tr>'+keys.map(k=>`<tr><td>${esc(k)}</td><td>${esc(typeof get(k)==='object'?JSON.stringify(get(k)):get(k))}</td><td>${fmt(age(k),1)} s</td><td>${fmt(last.ros?.[k]?.observed_hz)}</td></tr>`).join('')+'</table></div>'}
// SVG positive rotation is clockwise; positive servo displacement is LEFT.
function picture(front=0,rear=0){return `<svg class="diagram" viewBox="0 0 300 220" aria-label="Rover top view, commanded steering"><text x="120" y="18" fill="#a9c2d4">FRONT ↑</text><rect x="90" y="40" width="120" height="140" rx="16" fill="#102d40" stroke="#52caff"/><text x="120" y="111" fill="#fff">ATLAS</text>${[[75,65,'M3 FL',front],[225,65,'M4 FR',front],[75,161,'M1 RL',rear],[225,161,'M2 RR',rear]].map(([x,y,l,a])=>`<g transform="translate(${x},${y})"><rect x="-10" y="-21" width="20" height="42" rx="5" fill="#276486" transform="rotate(${-a})"/><text x="-25" y="39" fill="#b8d5e8" font-size="12">${l}</text></g>`).join('')}</svg>`}
function setPage(){page=location.hash.slice(1);if(!names[page])page='overview';$('nav').innerHTML=Object.entries(names).map(([k,v])=>`<button data-page="${k}" class="${page===k?'active':''}">${v}</button>`).join('');$('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>location.hash=b.dataset.page);clearTimeout(cameraTimer);$('tools').innerHTML=`<h2>${names[page]}</h2>`;
 if(page==='overview')$('tools').innerHTML+='<button data-test="hardware">RUN NON-MOTION HARDWARE CHECK</button>';
 if(page==='imu')$('tools').innerHTML+='<p>Keep ATLAS stationary. Ten seconds of existing IM10A telemetry; no calibration writes.</p><button data-test="imu">START 10-SECOND STATIONARY OBSERVATION</button>';
 if(page==='gnss')$('tools').innerHTML+='<button data-test="gnss">START 10-SECOND GNSS OBSERVATION</button>';
 if(page==='distance')$('tools').innerHTML+='<div class="controls"><label>Sensor <select id="side"><option>front</option><option>rear</option><option>left</option><option>right</option></select></label><label>Known distance (cm) <input id="known" type="number" min="1" max="1000" value="100"></label><button data-test="distance">CAPTURE 10 SECONDS</button></div>';
 if(page==='steering')steeringTools();
 if(page==='encoders')$('tools').innerHTML+='<p class="estimated">PHYSICAL FEEDBACK: ENCODER COUNTS ONLY — wheel operation requires a motion test.</p><button disabled>ACTUATOR COMMISSIONING LOCKED</button>';
 $('tools').querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>start(b.dataset.test));
 if(page==='camera'){$('tools').innerHTML+='<p>Existing cached JPEG stream; no additional camera encoder.</p><img id="camera" class="camera" alt="ATLAS camera — waiting for a fresh frame">';cameraControls();cameraTick()}
 render();
}
async function request(payload){let r=await fetch('/api/commissioning',{method:'POST',headers:{'Content-Type':'application/json','X-Atlas-Wifi':'1'},body:JSON.stringify(payload),signal:AbortSignal.timeout(5000)});let d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
async function start(kind){if(!confirm('Confirm ATLAS is stationary. This observes data only and will NOT move hardware.'))return;try{await request({action:'test',kind,side:$('side')?.value,known_mm:Number($('known')?.value)*10});$('message').textContent='Observation started. No movement commands sent.'}catch(e){$('message').textContent=e.message}}
function render(){if(!last.ros)return;const d=last.ros;let html='';
 // Use the owner's saved centres, not source-code defaults after calibration.
 if(live('steering_calibration',1)){const saved=obj('steering_calibration').saved;if(saved)for(const side of ['front','rear'])config.steering[side]={...config.steering[side],...saved[side]};}
 if(page==='overview'){html='<div class="grid">'+Object.entries(names).filter(([k])=>k!=='overview').map(([k,v])=>`<a class="card" href="#${k}"><h3>${v}</h3><span>Inspect live details →</span></a>`).join('')+'</div>';let checks=last.check?.checks||[];html+='<h3>Live telemetry check · not physical verification</h3><div class="scroll"><table><tr><th>Subsystem</th><th>Result</th><th>Meaning</th></tr>'+checks.map(c=>`<tr><td>${esc(c.name)}</td><td class="${c.state}">${esc(c.state)}</td><td>${esc(c.scope)}</td></tr>`).join('')+'</table></div>'}
 if(page==='steering'){let f=config.steering?.front||{},r=config.steering?.rear||{};html=picture((get('front_steer')??f.center)-f.center,(get('rear_steer')??r.center)-r.center)+'<div class="grid">'+tile('Front command',fmt(get('front_steer'),1)+'°','command',`Centre ${f.center} • left ${f.left} • right ${f.right} • servo ${f.servo_id}`)+tile('Rear command',fmt(get('rear_steer'),1)+'°','command',`Centre ${r.center} • left ${r.left} • right ${r.right} • servo ${r.servo_id}`)+tile('Actual position','NOT AVAILABLE','estimated','No position feedback; no position-error calculation')+tile('Raw PWM µs','NOT REPORTED','estimated','Yahboom API uses integer servo-angle commands; no invented microsecond precision')+'</div><p>Diagram is commanded servo displacement, not measured tyre geometry. Independent saved limits shown above; direction mapping needs physical verification.</p>'+rows(['front_steer','rear_steer','steer_mode','control_policy'])}
 if(page==='camera'){html='<div class="grid">'+tile('PCA command report',get('pca_status'),'command','Pulse widths, not measured camera angles')+tile('Physical position','NOT AVAILABLE','estimated','No pan/tilt position sensor installed')+'</div>'+rows(['camera_servo_status','camera_info','camera_tracking_status'])}
 if(page==='encoders'){const h=obj('encoder_health');html=picture()+'<p class="estimated">'+esc(h.reason||'Health unavailable')+'</p><div class="grid">';for(let i=1;i<=4;i++){let key='enc_m'+i,cur=d[key],prev=encoderPrevious[key],rate=null,delta=null;if(cur&&prev&&cur.sample_time>prev.t){delta=cur.value-prev.v;rate=delta/(cur.sample_time-prev.t)}if(cur&&(!prev||cur.sample_time>prev.t))encoderPrevious[key]={t:cur.sample_time,v:cur.value};let cpr=config.counts_per_revolution?.[i-1],sign=config.encoder_forward_sign?.[i-1];html+=tile(`M${i} · ${config.motor_locations?.[i-1]}`,get(key),'measured',`${h.excluded_encoders?.includes(i)?'EXCLUDED / UNVERIFIED':'Selected feedback'} • age ${fmt(age(key),1)}s`)+tile(`M${i} calculated rate`,rate===null?'Awaiting next sample':fmt(rate,1)+' counts/s','estimated',`Δ ${delta??'--'} • ${rate===null?'direction unknown':rate===0?'no count change':rate*sign>0?'configured FORWARD':'configured REVERSE'} • ${fmt(rate===null?null:rate*sign/cpr*60,1)} RPM (provisional CPR ${cpr})`)}html+='</div><p>CPR/gear ratio are not inferred from motor commands. Gear ratio: not separately verified. RPM uses legacy scale and must be rechecked after motor replacement. Fresh zero counts do not prove a working encoder.</p>'+rows(['encoder_health','cmd_vel','odom'])}
 if(page==='imu'){const f=obj('imu_full');html='<div class="grid">'+['imu_roll','imu_pitch','imu_yaw'].map(k=>tile(k,fmt(get(k))+'°')).join('')+['gx','gy','gz','ax','ay','az','mx_raw','my_raw','mz_raw'].map(k=>tile(k,fmt(f[k],4),'measured',k.startsWith('g')?'rad/s':k.startsWith('a')?'m/s²':'sensor-native raw units, not µT')).join('')+'</div><p class="estimated">'+esc(f.role)+' • '+esc(f.navigation_fusion)+'</p><p>Temperature: not supplied. Sensor calibration, mounting correction, software bias and EKF fusion are separate steps.</p><canvas id="chart" width="1000" height="110"></canvas><p class="muted">30-second sensor yaw history; not validated navigation heading.</p>'+rows(['imu_full','board_imu_heading'])}
 if(page==='distance'){let status=String(get('us_status')||'');html='<div class="grid">'+['front','left','right','rear'].map((side,i)=>tile(side.toUpperCase(),status.includes(['F','L','R','B'][i]+'=DISABLED')?'DISABLED':live('us_'+side,3)&&get('us_'+side)>0?fmt(get('us_'+side),0)+' mm':'NO VALID ECHO','measured',`Age ${fmt(age('us_'+side),1)}s • accepted physical range not commissioned`)).join('')+'</div><p>Locations: FRONT ↑ · LEFT ← ATLAS → RIGHT · REAR ↓. No ToF device assumed. Front/rear enabled status comes from MCU telemetry.</p>'+rows(['us_status','lidar','radar','radar_decoder_status'])}
 if(page==='gnss'){const g=obj('gps_diagnostics'),fix=obj('gps_fix');html='<div class="grid">'+tile('Fix',g.fix_valid?'VALID FIX':'NO FIX',g.fix_valid?'measured':'estimated','Fresh NMEA is not a position fix')+tile('Latitude',g.fix_valid?fmt(fix.lat,7):'UNAVAILABLE')+tile('Longitude',g.fix_valid?fmt(fix.lon,7):'UNAVAILABLE')+tile('Satellites used',g.satellites_used)+tile('HDOP',g.hdop,'estimated','Dilution of precision; not accuracy in metres')+'</div>'+rows(['gps_receiver_status','gps_diagnostics','gps_fix','gps_const'])}
 if(page==='other')html=rows(['i2c_status','outside_status','outside_temperature','outside_humidity','outside_pressure','outside_gas','thermal_status','bms_percent','bms_voltage','bms_current','jetson_power_status','radar_decoder_status']);
 if(page==='system'){html='<p>Cached service state. Process active does not prove sensor health; inactive on-demand navigation can be intentional.</p><div class="scroll"><table><tr><th>Service</th><th>State</th></tr>'+(diag.services||[]).map(s=>`<tr><td>${esc(s.unit||s.name)}</td><td>${esc(s.active)}</td></tr>`).join('')+'</table></div>'+rows(['control_policy','encoder_health','agent_team_status','carrier_status','joy']);}
 $('content').innerHTML=html;let active=last.state?.active;document.querySelectorAll('[data-test]').forEach(b=>b.disabled=!!active||!alive);if(active)$('message').textContent=`${active.kind}: observation running (${active.duration_s}s maximum sampling window)`;else if(last.state?.last){let r=last.state.last;$('message').textContent=`Last ${r.kind}: ${r.state} — ${r.reason||r.scope||'Observation saved; view history.'}`}
 if(page==='imu'){let c=$('chart'),g=c.getContext('2d'),points=trail.filter(p=>Number.isFinite(p.y));if(points.length>1){let lo=Math.min(...points.map(p=>p.y)),hi=Math.max(...points.map(p=>p.y));g.strokeStyle='#53e7b1';g.beginPath();points.forEach((p,i)=>{let x=1000*(p.t-(Date.now()-30000))/30000,y=100-90*(p.y-lo)/Math.max(.1,hi-lo);i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke();g.fillStyle='#a9c2d4';g.fillText(`${lo.toFixed(2)}° .. ${hi.toFixed(2)}°`,10,12)}}
}
async function cameraTick(){if(page!=='camera'||document.hidden)return;let img=$('camera');if(!img)return;if(live('camera_info',2)){img.src='/camera.jpg?t='+Date.now();img.style.opacity='1'}else{img.removeAttribute('src');img.alt='Camera stale / unavailable';img.style.opacity='.4'}cameraTimer=setTimeout(cameraTick,500)}
function cameraControls(){
 $('tools').innerHTML+='<p>Keep hands clear. One bounded move per tap; manual commands pause face tracking. Pulse reports are not physical position feedback.</p><label>Step <select id="cameraStep"><option value="25">Fine · 25 µs</option><option value="50">50 µs</option><option value="100">100 µs</option></select></label><div class="controls">'+[['tilt',-1,'↑ UP'],['pan',-1,'← LEFT'],['center',0,'RETURN HOME'],['pan',1,'RIGHT →'],['tilt',1,'DOWN ↓']].map(([a,d,l])=>`<button data-camera-axis="${a}" data-camera-dir="${d}">${l}</button>`).join('')+'</div><p id="cameraResult">Uses existing UNO camera owner and 700–2300 µs limits. Home remains the existing saved setup; changing home is not enabled here.</p>';
 let pending=false;
 $('tools').querySelectorAll('[data-camera-axis]').forEach(b=>b.onclick=async()=>{
  if(pending)return;
  if(!live('camera_servo_status',2)||!String(get('camera_servo_status')).startsWith('online ')){ $('cameraResult').textContent='Camera controller stale/offline; no command sent';return; }
  if(b.dataset.cameraAxis==='center'&&!confirm('Return camera to its configured home position? Keep hands clear.'))return;
  pending=true;const buttons=$('tools').querySelectorAll('[data-camera-axis]');buttons.forEach(x=>x.disabled=true);
  try{const r=await request({action:'camera',axis:b.dataset.cameraAxis,direction:Number(b.dataset.cameraDir),step_us:Number($('cameraStep').value)});if($('cameraResult'))$('cameraResult').textContent=r.message||'Command requested — confirm physical movement';}catch(e){if($('cameraResult'))$('cameraResult').textContent=e.message;}finally{pending=false;buttons.forEach(x=>x.disabled=false)}
 });
}
async function poll(){if(busy||document.hidden)return;busy=true;try{let r=await fetch('/api/commissioning',{cache:'no-store',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error('HTTP '+r.status);last=await r.json();config=last.configuration;alive=true;$('connection').textContent='TELEMETRY CONNECTED · actuator authority remains with existing owners';$('config').textContent=JSON.stringify(config,null,2);trail.push({t:Date.now(),y:get('imu_yaw')});trail=trail.filter(p=>Date.now()-p.t<30000).slice(-160);if(page==='system'&&Date.now()-diagTime>10000){diagTime=Date.now();diag=await fetch('/api/diagnostics',{cache:'no-store',signal:AbortSignal.timeout(4000)}).then(r=>r.json())}render()}catch(e){alive=false;$('connection').textContent='DISCONNECTED / STALE — displayed values are last received, NOT live';$('content').style.opacity='.4';document.querySelectorAll('[data-test]').forEach(b=>b.disabled=true)}finally{if(alive)$('content').style.opacity='1';busy=false}}
$('stop').onclick=async()=>{try{await request({action:'stop'});$('message').textContent='Stop requested. Confirm physical stop and live stop latch; remote neutral LB hold is required to release.'}catch(e){$('message').textContent='STOP NOT CONFIRMED — USE REMOTE STOP: '+e.message}};
$('historyBtn').onclick=async()=>{try{$('history').textContent=JSON.stringify(await fetch('/api/commissioning/history',{cache:'no-store'}).then(r=>r.json()),null,2)}catch{$('history').textContent='History unavailable'}};
$('export').onclick=()=>{let a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({configuration:config,last_observation:last.state?.last},null,2)],{type:'application/json'}));a.href=url;a.download='atlas-commissioning-observations.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
window.addEventListener('hashchange',setPage);document.addEventListener('visibilitychange',()=>{if(!document.hidden){poll();clearTimeout(cameraTimer);cameraTick()}});setPage();poll();setInterval(poll,200);
