const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const code = fs.readFileSync(__dirname+'/atlas_diagnostics_ui.js','utf8');
const python = fs.readFileSync(__dirname+'/atlas_status_web.py','utf8');
// Validate the modern main page script without running drive bindings.
const inline = python.slice(python.lastIndexOf('<script>')+8).split('</script>')[0];
new vm.Script(inline);
const context = vm.createContext({val:(r,k,d)=>r[k]?.value??d,recent:(r,k,s)=>r[k]?.age<s,row:(a,b)=>`${a}:${b}\n`});
context.setInterval=()=>{};
vm.runInContext(code, context);
context.battery={bms_status:{age:1,value:JSON.stringify({ok:true,age_s:0,soc_percent:53.4,current_a:-2})}};
assert.equal(vm.runInContext('mainBattery(battery).state',context),'DISCHARGING');
context.battery.bms_status.value=JSON.stringify({ok:true,soc_percent:60,current_a:2});
assert.equal(vm.runInContext('mainBattery(battery).state',context),'CHARGING');
context.battery.bms_status.age=21;
assert.equal(vm.runInContext('mainBattery(battery).percent',context),null);
context.battery.bms_status={age:0,value:JSON.stringify({ok:true,soc_percent:100,current_a:0})};
assert.equal(vm.runInContext('mainBattery(battery).state',context),'FULL · IDLE');
const g={source:'SIM8230G USB GNSS',nmea_age_s:0.1,fix_valid:false,satellites_used:0,talkers:['GP','GL'],constellations:{GPS:{in_view:0,age_s:0.1},GLONASS:{in_view:0,age_s:0.1}}};
context.r={gps_diagnostics:{age:0.1,value:JSON.stringify(g)},gps_fix:{age:0.1,value:{status:-1}}};
let bars = vm.runInContext('diagnosticConstellations(r)',context);
assert(!bars.includes('DETECTED'));assert(bars.includes('0 SAT'));assert(!/width:(?!0%)[0-9]+%/.test(bars));
g.constellations.GPS.in_view=5;context.r.gps_diagnostics.value=JSON.stringify(g);
assert(vm.runInContext('diagnosticConstellations(r)',context).includes('5 SAT'));
context.r.gps_diagnostics.age=20;
bars=vm.runInContext('diagnosticConstellations(r)',context);assert(!bars.includes('5 SAT'));assert(bars.includes('STALE'));
assert(!vm.runInContext('gnssInfo(r).fixed',context));
context.r.gps_diagnostics.age=0.1;g.fix_valid=true;context.r.gps_diagnostics.value=JSON.stringify(g);
context.r.gps_fix.value={status:0,lat:0,lon:0};
assert(vm.runInContext('gnssSummary(r)',context).includes('0.000000, 0.000000'));
assert.equal(vm.runInContext("diagEscape('<script>')",context),'&lt;script&gt;');
console.log('PASS: modern JS syntax; real zero/positive/stale satellite bars; stale fix; equator coordinates; HTML escaping');
