teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 4
    enable_turbo_button: 5
    axis_linear:
      x: 1
    scale_linear:
      x: -0.45
    scale_linear_turbo:
      x: -0.65
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.20
    scale_angular_turbo:
      yaw: 1.60
    inverted_reverse: false
