#!/usr/bin/env python3
"""Build the V2 mapping, commissioning and Wi-Fi pages from their V1 sources.

The V1 markup and inline scripts are kept verbatim; only these edits are applied, and each one
must match the expected number of times so V1 drift fails the build instead of silently diverging:
  * <html> gets the V2 page classes; base.css + pages.css are linked after the V1 <style>
    (so V2 styling overrides by cascade order, never by editing V1 rules);
  * links to "/" (command center) point to "/v2/"; the 1.19 MB /logo.png becomes a 2 KB WebP;
  * a bottom dock is appended: mapping and Wi-Fi get an E-STOP that sends exactly the
    command-center request (form POST "/" action=e_stop); commissioning keeps its own
    LATCH DRIVE STOP button (#stop), which CSS pins in the dock, so no second stop is added.
Usage: build_pages.py <repo>/project_atlas   (writes web/v2/{mapping,commissioning,wifi}.html)
"""
import ast, hashlib, sys
from pathlib import Path

root = Path(sys.argv[1] if len(sys.argv) > 1 else Path(__file__).resolve().parents[2])
scripts, out = root / 'scripts', root / 'web' / 'v2'


def wifi_page():
    tree = ast.parse((scripts / 'atlas_wifi_web.py').read_text(encoding='utf-8'))
    for node in tree.body:
        if isinstance(node, ast.Assign) and getattr(node.targets[0], 'id', '') == 'PAGE':
            return node.value.value
    raise SystemExit('PAGE not found in atlas_wifi_web.py')


ESTOP_DOCK = '''<div class="v2dock" role="region" aria-label="Emergency stop">
<button class="v2estop" id="v2Estop" type="button"><svg class="v2icon" aria-hidden="true"><use href="/v2/assets/icons.svg#i-stop"/></svg>E-STOP</button>
<span class="v2dock-msg" id="v2EstopMsg" role="status">Sends one zero-speed command. Keep the physical remote stop available.</span>
<a class="v2dock-link" href="{classic}">Classic page</a></div>
<script src="/v2/estop.js" defer></script>'''
LATCH_DOCK = '''<div class="v2dock v2dock-latch" role="region" aria-label="Drive stop">
<span class="v2dock-msg">LATCH DRIVE STOP latches drive at zero. Releasing it needs the remote: sticks neutral, hold LB.</span>
<a class="v2dock-link" href="{classic}">Classic page</a></div>'''

PAGES = {
    'mapping': dict(src=lambda: (scripts / 'atlas_mapping.html').read_text(encoding='utf-8'), classic='/mapping',
                    dock=ESTOP_DOCK, html=('<html lang="en">', 1), home=1, logo=1),
    'commissioning': dict(src=lambda: (scripts / 'atlas_commissioning.html').read_text(encoding='utf-8'), classic='/commissioning',
                          dock=LATCH_DOCK, html=('<html lang="en">', 1), home=1, logo=0),
    'wifi': dict(src=wifi_page, classic='/wifi', dock=ESTOP_DOCK, html=('<html>', 1), home=1, logo=0),
}


def sub(text, old, new, expect, what):
    n = text.count(old)
    assert n == expect, f'{what}: expected {expect} match(es) of {old!r}, found {n}'
    return text.replace(old, new)


for name, p in PAGES.items():
    src = p['src']()
    html = src
    tag, n = p['html']
    html = sub(html, tag, f'<html lang="en" class="v2page v2-{name}">', n, f'{name} html tag')
    html = sub(html, '</head>', '<link rel="preload" href="/v2/assets/michroma-latin-400.woff2" as="font" type="font/woff2" crossorigin>'
               '<link rel="stylesheet" href="/v2/base.css"><link rel="stylesheet" href="/v2/pages.css"></head>', 1, f'{name} head')
    html = sub(html, 'href="/"', 'href="/v2/"', p['home'], f'{name} home link')
    if p['logo']:
        html = sub(html, 'src="/logo.png"', 'src="/v2/assets/atlas-logo-96.webp" width="44" height="44"', p['logo'], f'{name} logo')
    if name == 'mapping':   # the V1 note would be untrue once the dock E-STOP exists
        html = sub(html, 'This page observes ROS data only. It creates no cloud-to-motor or browser-to-motor path.',
                   'This page observes ROS data. Its only control path is E-STOP (one zero-speed command); it sends no drive or navigation commands.',
                   1, 'mapping overlay note')
    html = sub(html, '</body>', p['dock'].format(classic=p['classic']) + '</body>', 1, f'{name} body end')
    banner = (f'<!-- ATLAS Glass UI V2: generated by tools/ui_v2/build_pages.py from the V1 {p["classic"]} page '
              f'(sha256 {hashlib.sha256(src.encode()).hexdigest()[:16]}). Do not edit by hand. -->\n')
    end = html.index('>') + 1                     # keep <!doctype html> first (standards mode)
    (out / f'{name}.html').write_text(html[:end] + '\n' + banner + html[end:], encoding='utf-8')
    print('wrote', name, len(html), 'bytes')
