#!/usr/bin/env python3
"""Build web/v2/command.js from the V1 command-center page (verbatim + documented patches).

Input: the HTML that rover-status-web serves at "/" (render_control_page output).
Every patch must match exactly once, so drift in V1 fails the build instead of silently diverging.
Usage: build_command_js.py v1_index.html web/v2/command.js
"""
import hashlib, re, sys
src = open(sys.argv[1], encoding='utf-8').read()
scripts = [b for a, b in re.findall(r'<script([^>]*)>(.*?)</script>', src, re.S) if 'src=' not in a]
assert len(scripts) == 1, 'expected exactly one inline script in V1 page'
js = scripts[0]
PATCHES = [
    ('P1 camera frames only while the camera (or its detail view) is visible; optional data saver',
     "function pollLatestCameraFrame(force=false){\n if(document.hidden)return;",
     "function pollLatestCameraFrame(force=false){\n if(document.hidden)return;\n if(window.atlasV2&&!window.atlasV2.cameraWanted(force))return; // V2 P1"),
    ('P2 radar polling only while the radar panel (or its detail view) is visible',
     "async function pollRadar(){try{",
     "async function pollRadar(){if(window.atlasV2&&!window.atlasV2.radarWanted())return; /* V2 P2 */try{"),
    ('P3 Wi-Fi setup link opens the V2 Wi-Fi page (same server endpoints)',
     '<a class="btn" href="/wifi">',
     '<a class="btn" href="/v2/wifi">'),
    ('P4a E-STOP lock state: a press that starts while no pointer is down clears it',
     "let hold=null;",
     "let hold=null;let estopLock=false;const v2Down=new Set();"
     "addEventListener('pointerdown',e=>{if(!v2Down.size)estopLock=false;v2Down.add(e.pointerId)},true);"
     "for(const t of ['pointerup','pointercancel'])addEventListener(t,e=>v2Down.delete(e.pointerId),true); /* V2 P4a */"),
    ('P4b drive cannot start while the E-STOP lock is set (a finger still down from before the E-STOP)',
     "function beginDrive(b){stopDrive(false);",
     "function beginDrive(b){if(estopLock)return; /* V2 P4b */stopDrive(false);"),
    ('P4c E-STOP fires on pointerdown (a second-finger tap produces no click while another finger is down), '
     'cancels the local hold-to-drive repeat, then sends the same e_stop request; keyboard activation still works',
     "$('stop').onclick=()=>post({action:'e_stop'});",
     "window.atlasEstop=()=>{estopLock=true;stopDrive(false);return post({action:'e_stop'})};"
     "$('stop').onpointerdown=e=>{e.preventDefault();atlasEstop()};$('stop').onclick=e=>{if(e.detail===0)atlasEstop()}; /* V2 P4c */"),
]
for name, old, new in PATCHES:
    n = js.count(old)
    assert n == 1, f'{name}: expected 1 match, found {n}'
    js = js.replace(old, new)
header = ('/* ATLAS Glass UI V2 command-center logic.\n'
          f' * Generated by tools/ui_v2/build_command_js.py from the V1 page (sha256 {hashlib.sha256(src.encode()).hexdigest()[:16]}).\n'
          ' * The V1 inline script is copied verbatim except for these patches:\n'
          + ''.join(f' *   {name}\n' for name, _, _ in PATCHES) +
          ' * All request paths, bodies, repeat rates and stop-on-release handlers are unchanged. */\n')
open(sys.argv[2], 'w', encoding='utf-8').write(header + js)
print('wrote', sys.argv[2], len(js), 'bytes;', len(PATCHES), 'patches applied')
