#!/usr/bin/env python3
"""Build a staged, self-checking Jetson deployment package for ONE approved stage.

A package never restarts anything. Its install.sh:
  1. refuses to run unless every patch applies cleanly (`patch --dry-run`) to the live files;
  2. copies every file it will touch into ~/project_atlas/data/backups/<date>-<stage>/ and writes
     ROLLBACK.sh there (restores originals, removes added files) BEFORE changing anything;
  3. applies the patches, copies new files, byte-compiles changed Python, and checks the result
     hashes when the live files matched the recorded baseline;
  4. prints (does not run) the single service restart the stage needs.

Usage: make_package.py <stage-name> <base-commit> <head-commit> <out-dir> -- <repo paths...>
Paths may be files or directories under project_atlas/, optionally as path@BASE..HEAD to take that
path's change from a different commit range (e.g. only the /v2 route hook of a file that later
commits changed again). Modified files ship as unified diffs; files absent at the base ship whole.
"""
import hashlib, io, os, subprocess, sys, tarfile, textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
PREFIX = 'project_atlas/'


def git(*a, binary=False):
    out = subprocess.run(['git', '-C', str(REPO), *a], check=True, capture_output=True).stdout
    return out if binary else out.decode()


def show(commit, path):
    r = subprocess.run(['git', '-C', str(REPO), 'show', f'{commit}:{path}'], capture_output=True)
    return r.stdout if r.returncode == 0 else None


def main():
    stage, base, head, out = sys.argv[1:5]
    assert sys.argv[5] == '--'
    paths, ranges = [], {}
    for arg in sys.argv[6:]:
        p, _, rng = arg.partition('@')
        b, h = rng.split('..') if rng else (base, head)
        for f in git('ls-tree', '-r', '--name-only', h, '--', p).split():
            paths.append(f); ranges[f] = (b, h)
    paths = sorted(set(paths))
    assert paths and all(p.startswith(PREFIX) for p in paths), paths
    out = Path(out) / stage
    (out / 'files').mkdir(parents=True, exist_ok=True); (out / 'patches').mkdir(exist_ok=True)
    manifest, patched, added = [], [], []
    for p in paths:
        rel = p[len(PREFIX):]
        b, h = ranges[p]
        old, new = show(b, p), show(h, p)
        if old == new:
            continue
        sha = lambda b: hashlib.sha256(b).hexdigest()
        if old is None:
            dst = out / 'files' / rel; dst.parent.mkdir(parents=True, exist_ok=True); dst.write_bytes(new)
            added.append(rel); manifest.append(f'ADD {rel} {sha(new)}')
        else:
            diff = git('diff', '--no-color', '-U5', b, h, '--', p)
            diff = diff.replace(f'a/{p}', f'a/{rel}').replace(f'b/{p}', f'b/{rel}')
            name = rel.replace('/', '__') + '.patch'
            (out / 'patches' / name).write_text(diff)
            patched.append((rel, name)); manifest.append(f'PATCH {rel} range={b[:9]}..{h[:9]} base={sha(old)} result={sha(new)}')
    (out / 'MANIFEST').write_text(f'stage {stage}\nbase {git("rev-parse", base).strip()}\nhead {git("rev-parse", head).strip()}\n'
                                  + '\n'.join(manifest) + '\n')
    py = [r for r, _ in patched if r.endswith('.py')] + [r for r in added if r.endswith('.py')]
    install = f'''#!/usr/bin/env bash
# ATLAS staged deployment: {stage}. Generated by tools/deploy/make_package.py. Restarts NOTHING.
set -euo pipefail
PKG="$(cd "$(dirname "$0")" && pwd)"; ROOT="${{ATLAS_ROOT:-$HOME/project_atlas}}"
STAMP="$(date +%Y-%m-%d-%H%M%S-%N)"; BK="$ROOT/data/backups/$STAMP-{stage}"
cd "$ROOT"
echo "== dry run"; {''.join(f'patch -p1 --dry-run --forward --no-backup-if-mismatch -s < "$PKG/patches/{n}"; ' for _, n in patched) or 'true; '}
for f in {' '.join(added) or '""'}; do [ -z "$f" ] || [ ! -e "$f" ] || {{ echo "refusing: $f already exists"; exit 2; }}; done
echo "== backup to $BK"; mkdir -p "$BK/orig"
for f in {' '.join(r for r, _ in patched) or '""'}; do [ -z "$f" ] || {{ mkdir -p "$BK/orig/$(dirname "$f")"; cp -a "$f" "$BK/orig/$f"; }}; done
printf '%s\\n' {' '.join(added) or '""'} > "$BK/added.txt"
cat > "$BK/ROLLBACK.sh" <<'RB'
#!/usr/bin/env bash
# Restore the files changed by stage {stage} and remove the files it added. Restarts nothing.
set -euo pipefail
BK="$(cd "$(dirname "$0")" && pwd)"; ROOT="${{ATLAS_ROOT:-$HOME/project_atlas}}"; cd "$ROOT"
(cd "$BK/orig" && find . -type f -print0) | while IFS= read -r -d '' f; do cp -a "$BK/orig/$f" "$ROOT/$f"; echo "restored $f"; done
while read -r f; do [ -z "$f" ] || {{ rm -f -- "$ROOT/$f" && echo "removed $f"; }}; done < "$BK/added.txt"
find "$ROOT/web/v2" -depth -type d -empty -delete 2>/dev/null || true
echo "rollback of {stage} complete; restart the affected service when coordinated."
RB
chmod +x "$BK/ROLLBACK.sh"; cp "$PKG/MANIFEST" "$BK/"
echo "== apply"; {''.join(f'patch -p1 --forward --no-backup-if-mismatch -s < "$PKG/patches/{n}"; ' for _, n in patched) or 'true; '}
(cd "$PKG/files" && find . -type f -print0) | while IFS= read -r -d '' f; do mkdir -p "$(dirname "$f")"; cp "$PKG/files/$f" "$f"; done
{'python3 -m py_compile ' + ' '.join(py) + ' && echo "byte-compile ok"' if py else 'true'}
echo "== result hashes (MATCH expected when the live files were the recorded baseline)"
grep -E '^(PATCH|ADD) ' "$PKG/MANIFEST" | while read -r kind f rest; do
  want="${{rest##*result=}}"; [ "$kind" = ADD ] && want="$rest"
  got="$(sha256sum "$f" | cut -d' ' -f1)"; [ "$got" = "$want" ] && echo "MATCH  $f" || echo "DIFFER $f (live baseline differed; patch applied cleanly)"
done
echo "== installed. Backup and ROLLBACK.sh: $BK"
echo "== NOT restarted. When coordinated (rover parked): see RESTART in $PKG/README.txt"
'''
    (out / 'install.sh').write_text(install); os.chmod(out / 'install.sh', 0o755)
    here = Path(__file__).resolve().parent
    readme = here / 'readmes' / f'{stage}.txt'
    (out / 'README.txt').write_text(readme.read_text() if readme.exists() else f'ATLAS stage {stage}\n')
    (out / 'verify.sh').write_text((here / 'verify.sh').read_text()); os.chmod(out / 'verify.sh', 0o755)
    print(f'{stage}: {len(patched)} patched, {len(added)} added -> {out}')


if __name__ == '__main__':
    main()
